# cat services_nginx.yml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    run: nginx
  name: nginxhelm
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: nginxhelm
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort