# cat services_nginx.yml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: giropops
    run: nginx
  name: primeiro-deployment
  namespace: default
spec:
  clusterIP: 10.102.126.165
  clusterIPs:
  - 10.102.126.165
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32573
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort